from .category import CategorySerializer
from .comment import CommentSerializer
from .discount import DiscountSerializer
from .inventory import InventorySerializer
from .like import LikeSerializer
from .product_image import ProductImageSerializer
from .product import ProductSerializer
from .rating import RatingSerializer
from .vendor import VendorSerializer
from .product_details import ProductDetailsSerializer
from .vendor_id import VendorIDSerializer
from .product_id import ProductIDSerializer